plugins {
    id 'groovy'
}

group = 'org.teste'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.apache.groovy:groovy:5.0.8'

    testImplementation 'org.spockframework:spock-core:2.4-groovy-5.0'
    testImplementation 'org.apache.groovy:groovy:5.0.8'

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}